name: 'Publish Testly Results'
description: 'Publish Testly Results'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  file:
    description: 'Path where xml test file can be found'
    required: true
  api:
    description: 'API key to use actions'
    required: true
#outputs:
#  tag:
#    description: 'Latest tag'
runs:
  using: 'node12'
  main: 'dist/index.js'

# runs:
#   using: 'composite'
#   steps:
#     # If it's a commit
#     - name: list files
#       shell: bash
#       run: |
#         ls -R .
#         ls -R /
