name: Continuous Integration
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  ci:
    name: Test Testly
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: 'Test'
        id: test
        uses: ./
	with:
	  file: 't'
          api: 'o'
